services:
  backend:
    build: ./konecta_back
    ports:
      - "5000:5000"
    volumes:
      - ./konecta_back:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - DB_USER=andrekasjas
      - DB_PASSWORD=admin
      - DB_HOST=localhost
      - DB_NAME=konecta
      - DB_PORT=5432
      - JWT_SECRET=konecta
      
  frontend:
    build: ./konecta_front
    ports:
      - "80:80"
    volumes:
      - ./konecta_front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_ROUTE=http://localhost:5000/api/v1
    depends_on:
      - backend