services:
 backend:
    build: ./konecta_back
    ports:
      - "5000:5000"
    volumes:
      - ./konecta_back:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - DB_USER=andrekasjas
      - DB_PASSWORD=admin
      - DB_HOST=localhost
      - DB_NAME=konecta
      - DB_PORT=5432
      - JWT_SECRET=konecta