services:
  backend:
    build: ./konecta_back
    ports:
      - "5000:5000"
    volumes:
      - ./konecta_back:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_USER=andrekasjas
      - DB_PASSWORD=admin
      - DB_HOST=localhost
      - DB_NAME=konecta
      - DB_PORT=5432
      - JWT_SECRET=konecta

  frontend:
    build: ./konecta_front
    ports:
      - "80:80"
    volumes:
      - ./konecta_front:/app
    environment:
      - NODE_ENV=development
      - VITE_API_ROUTE=http://localhost:3000/api/v1
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: andrekasjas
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: konecta
    ports:
      - 5432:5432
    volumes:
      - ./konecta_back/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: andresmogollob@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
