services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: andrekasjas
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: konecta
    ports:
      - 5432:5432
    volumes:
      - ./konecta_back/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: andresmogollob@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres