-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.empleado
(
    "ID" serial NOT NULL,
    "FECHA_INGRESO" timestamp with time zone NOT NULL,
    "NOMBRE" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "SALARIO" double precision NOT NULL,
    "ID_USUARIO" integer NOT NULL,
    CONSTRAINT empleado_pkey PRIMARY KEY ("ID"),
    CONSTRAINT "empleado_ID_USUARIO_key" UNIQUE ("ID_USUARIO")
);

CREATE TABLE IF NOT EXISTS public.solicitud
(
    "ID" serial NOT NULL,
    "CODIGO" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "DESCRIPCION" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "RESUMEN" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "ID_EMPLEADO" integer NOT NULL,
    CONSTRAINT solicitud_pkey PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    "ID" serial NOT NULL,
    "USERNAME" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "EMAIL" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "PASSWORD" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "ROL" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY ("ID"),
    CONSTRAINT "usuario_EMAIL_key" UNIQUE ("EMAIL"),
    CONSTRAINT "usuario_USERNAME_key" UNIQUE ("USERNAME")
);

ALTER TABLE IF EXISTS public.empleado
    ADD CONSTRAINT "empleado_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO")
    REFERENCES public.usuario ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "empleado_ID_USUARIO_key"
    ON public.empleado("ID_USUARIO");


ALTER TABLE IF EXISTS public.solicitud
    ADD CONSTRAINT "solicitud_ID_EMPLEADO_fkey" FOREIGN KEY ("ID_EMPLEADO")
    REFERENCES public.empleado ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;